### ISSUE TITLE
phpunit failures

### ISSUE THREAD

**Issue by bytehead** [tchwork/utf8#53] opened 2015-10-14 16:43 UTC
I have some strange errors, basically related to my php-stack.

My installed php formulas (installed via homebrew on Mac OS X 10.10.5):
- php56
- php56-intl
- php56-mcrypt
- php56-mongo
- php56-xdebug

My versions:
- PHP 5.6.14
- intl Version 1.1.0
- ICU Version 55.1
- ICU Data version 55.1
- mcrypt 2.5.8
- mongo 1.5.8
- xdebug 2.3.3

phpunit output:

````bash
$ phpunit
PHPUnit 4.4.1 by Sebastian Bergmann.

Configuration read from dev/utf8/phpunit.xml.dist

.........E.EE.......................E.E...E......EE.SSSSSSSSS..  63 / 247 ( 25%)
...E.EE............E........................................... 126 / 247 ( 51%)
.......................................................E....E.. 189 / 247 ( 76%)
E.....E..E..............EEEEEEEEEEEEE..E..................

Time: 628 ms, Memory: 23.25Mb

1) Patchwork\Tests\PHP\Shim\IntlTest::testGrapheme_extract
grapheme_extract(): grapheme_extract: start not contained in string

dev/utf8/tests/Patchwork/Tests/PHP/Shim/IntlTest.php:35

2) Patchwork\Tests\PHP\Shim\IntlTest::testGrapheme_substr
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/tests/Patchwork/Tests/PHP/Shim/IntlTest.php:86

3) Patchwork\Tests\PHP\Shim\IntlTest::testGrapheme_strpos
grapheme_strpos(): grapheme_strpos: Empty delimiter

dev/utf8/tests/Patchwork/Tests/PHP/Shim/IntlTest.php:122

4) Patchwork\Tests\TurkishUtf8Test::testStrCmp
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/src/Patchwork/Utf8.php:578
dev/utf8/src/Patchwork/Utf8.php:574
dev/utf8/tests/Patchwork/Tests/TurkishUtf8Test.php:40

5) Patchwork\Tests\TurkishUtf8Test::testStristr
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/src/Patchwork/TurkishUtf8.php:74
dev/utf8/tests/Patchwork/Tests/TurkishUtf8Test.php:60

6) Patchwork\Tests\Utf8\BootupTest::testFilterRequestInputs
Normalizer::isNormalized(): Error converting string to UTF-16.

dev/utf8/src/Patchwork/Utf8/Bootup.php:210
dev/utf8/src/Patchwork/Utf8/Bootup.php:193
dev/utf8/tests/Patchwork/Tests/Utf8/BootupTest.php:51

7) Patchwork\Tests\Utf8\HhvmTest::test6
grapheme_strlen(): Error converting input string to UTF-16

dev/utf8/tests/Patchwork/Tests/Utf8/HhvmTest.php:37

8) Patchwork\Tests\Utf8\HhvmTest::test7
Normalizer::normalize(): Error converting input string to UTF-16

dev/utf8/tests/Patchwork/Tests/Utf8/HhvmTest.php:42

9) Patchwork\Tests\Utf8Test::testSubstr
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/tests/Patchwork/Tests/Utf8Test.php:98

10) Patchwork\Tests\Utf8Test::testStrCmp
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/src/Patchwork/Utf8.php:578
dev/utf8/src/Patchwork/Utf8.php:574
dev/utf8/tests/Patchwork/Tests/Utf8Test.php:156

11) Patchwork\Tests\Utf8Test::testStrpos
grapheme_strpos(): grapheme_strpos: Empty delimiter

dev/utf8/src/Patchwork/Utf8.php:238
dev/utf8/tests/Patchwork/Tests/Utf8Test.php:173

12) Patchwork\Tests\Utf8Test::testFilter
Normalizer::isNormalized(): Error converting string to UTF-16.

dev/utf8/src/Patchwork/Utf8.php:136
dev/utf8/src/Patchwork/Utf8.php:118
dev/utf8/tests/Patchwork/Tests/Utf8Test.php:412

13) Utf8StrlenTest::test_utf8_invalid
grapheme_strlen(): Error converting input string to UTF-16

dev/utf8/src/Patchwork/Utf8.php:234
dev/utf8/tests/php-utf8/Utf8StrlenTest.php:20

14) Utf8StrposTest::test_utf8_invalid
grapheme_strpos(): Error converting input string to UTF-16

dev/utf8/src/Patchwork/Utf8.php:238
dev/utf8/tests/php-utf8/Utf8StrposTest.php:28

15) Utf8StrposTest::test_empty_str
grapheme_strpos(): grapheme_strpos: Offset not contained in string

dev/utf8/src/Patchwork/Utf8.php:238
dev/utf8/tests/php-utf8/Utf8StrposTest.php:49

16) Utf8StrrposTest::test_utf8_invalid
grapheme_strrpos(): Error converting input string to UTF-16

dev/utf8/src/Patchwork/Utf8.php:242
dev/utf8/tests/php-utf8/Utf8StrrposTest.php:26

17) Utf8StrrposTest::test_empty_str
grapheme_strrpos(): grapheme_strpos: Offset not contained in string

dev/utf8/src/Patchwork/Utf8.php:242
dev/utf8/tests/php-utf8/Utf8StrrposTest.php:44

18) Utf8SubstrTest::test_utf8
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/tests/php-utf8/Utf8SubstrTest.php:14

19) Utf8SubstrTest::test_utf8_two
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/tests/php-utf8/Utf8SubstrTest.php:20

20) Utf8SubstrTest::test_utf8_zero
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/tests/php-utf8/Utf8SubstrTest.php:26

21) Utf8SubstrTest::test_utf8_zero_zero
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/tests/php-utf8/Utf8SubstrTest.php:32

22) Utf8SubstrTest::test_start_great_than_length
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/tests/php-utf8/Utf8SubstrTest.php:38

23) Utf8SubstrTest::test_compare_start_great_than_length
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/tests/php-utf8/Utf8SubstrTest.php:44

24) Utf8SubstrTest::test_length_beyond_string
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/tests/php-utf8/Utf8SubstrTest.php:50

25) Utf8SubstrTest::test_compare_length_beyond_string
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/tests/php-utf8/Utf8SubstrTest.php:56

26) Utf8SubstrTest::test_start_negative
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/tests/php-utf8/Utf8SubstrTest.php:62

27) Utf8SubstrTest::test_length_negative
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/tests/php-utf8/Utf8SubstrTest.php:68

28) Utf8SubstrTest::test_start_length_negative
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/tests/php-utf8/Utf8SubstrTest.php:74

29) Utf8SubstrTest::test_linefeed
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/tests/php-utf8/Utf8SubstrTest.php:80

30) Utf8SubstrTest::test_long_length
grapheme_substr(): grapheme_substr: length is beyond start

dev/utf8/src/Patchwork/Utf8.php:223
dev/utf8/tests/php-utf8/Utf8SubstrTest.php:86

31) Utf8ToAsciiTest::test_invalid_char
Normalizer::normalize(): Error converting input string to UTF-16

dev/utf8/src/Patchwork/Utf8.php:44
dev/utf8/tests/php-utf8/Utf8ToAsciiTest.php:26

FAILURES!                                           
Tests: 247, Assertions: 472, Errors: 31, Skipped: 9.
````

It's actually correlated to this line: https://github.com/php/php-src/blob/php-5.6.14/ext/intl/grapheme/grapheme_string.c#L854

Seems to be a PHP bug for me.
What do you think?

**Comment by nicolas-grekas** [comment] 2015-10-16 16:03
Does this patch fix the issue?
```diff
+++ b/src/Patchwork/Utf8.php
@@ -220,7 +220,7 @@ class Utf8
     public static function substr($s, $start, $len = 2147483647)
     {
         static $bug62759;
-        isset($bug62759) or $bug62759 = extension_loaded('intl') && '<C3><A0>' === grapheme_substr('<C3><A9><C3><A0>', 1, -2);
+        isset($bug62759) or $bug62759 = extension_loaded('intl') && '<C3><A0>' === @grapheme_substr('<C3><A9><C3><A0>', 1, -2);
 
         if ($bug62759) {
```

**Comment by bytehead** [comment] 2015-10-17 08:21
No, didn't work.

**Comment by leofeyer** [comment] 2015-10-22 11:39
I just found out that this issue only occurs with PhpUnit 4.8. It does not occur with PhpUnit 5. Which version are you using?

**Comment by bytehead** [comment] 2015-10-22 11:56
4.4.1

**Comment by leofeyer** [comment] 2015-10-22 13:37
Can you try it with `~5.0` please?

**Comment by bytehead** [comment] 2015-10-22 13:44
Negative.
Installed PHPUnit 5.0.7.

**Comment by leofeyer** [comment] 2015-10-22 14:13
It was worth a try :(

**Comment by bytehead** [comment] 2015-10-22 14:22
Definitely.

**Comment by nicolas-grekas** [comment] 2015-12-15 15:47
I'm sorry but I'm unable to reproduce, nor travis-ci... Please reopen I you think this is a bug that should be fixed here (vs an issue on your setup).

**Closed by nicolas-grekas** 2015-12-15 15:47 UTC

**Comment by bytehead** [comment] 2015-12-15 15:49
:+1: thanks!
