### ISSUE TITLE
PHP Fatal error (Allowed memory size exceeded) when using mb_strpos without iconv or mbstring installed

### ISSUE THREAD

**Issue by aembler** [tchwork/utf8#33] opened 2015-01-03 00:24 UTC
I believe there's a problem with the logic flow with how mb_strpos (and perhaps some other functions) work when neither iconv or mbstring is installed in PHP. (Note: if one or both of these is actually required then this may not technically be an issue, but I didn't see that one or both was required.) If neither of these is required, the functions get stuck in a loop.

**Comment by nicolas-grekas** [comment] 2015-01-04 16:57
Could you give me file+line info please?

**Comment by aembler** [comment] 2015-01-04 22:03
Yes, here's the full error in the log:

[Sun Jan 04 13:55:27 2015] [error] [client 127.0.0.1] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 40414 bytes) in /Users/andrewembler/git/concrete5-5.7.0/web/concrete/vendor/patchwork/utf8/class/Patchwork/PHP/Shim/Mbstring.php on line 310, referer: http://concrete5/index.php/install

Hope this helps

**Comment by nicolas-grekas** [comment] 2015-01-04 22:09
It looks like you have iconv?
So, iconv consumes memory?
Is their a way I can somehow reproduce the problem locally?

**Comment by aembler** [comment] 2015-01-05 15:08
This actually doesn't happen if I have either iconv or mbstring installed.
It only happens if both of them are not installed and that method gets run.
I think it just ends up recursing infinitely due to a logic error.

**Comment by nicolas-grekas** [comment] 2015-01-05 22:58
can you please test with ~1.1@dev ?

**Comment by nicolas-grekas** [comment] 2015-01-05 23:04
~1.1.26@dev

**Comment by aembler** [comment] 2015-01-06 20:10
Yep! That fixes it! Thanks for the quick response.

**Comment by nicolas-grekas** [comment] 2015-01-11 12:46
v1.1.27 released with the fix

**Closed by nicolas-grekas** 2015-01-11 12:46 UTC
